/* MER_DISTRIBUIDORA MAGU: */

CREATE TABLE VENDEDORES (
    VDR_CODIGO int PRIMARY KEY,
    VDR_NOME varchar(50),
    VDR_TELEFONE bigint
); 

CREATE TABLE CLIENTES (
    CLI_CODIGO int PRIMARY KEY,
    CLI_NOME varchar(50),
    CLI_TELEFONE bigint,
    CLI_EMAIL varchar(50),
    CLI_REFCOMERCIAL varchar(50),
    CLI_REFBANCARIA varchar(50),
    CLI_IE int,
    CLI_CNPJ int,
    CLI_LIMITE float,
    FK_VDR_CODIGO int,
    FK_TPC_CODIGO int, /* APENAS DOIS TIPOS (1,99 E MERCADO) */
    FK_REG_CODIGO int
);

CREATE TABLE REGIOES (
    REG_CODIGO int PRIMARY KEY,
    REG_NOME varchar(50),
    FK_VDR_CODIGO int
);

CREATE TABLE PEDIDOS (
    PED_CODIGO int PRIMARY KEY,
    PED_DATA date,
    PED_VALORINICIAL float,
    PED_DESCONTO float,
    PED_VALORFINAL float,
    PED_QNT_PAGAMENTOS int,
    FK_FRP_CODIGO int,
    FK_VDR_CODIGO int,
    FK_CLI_CODIGO int,
    FK_STF_CODIGO int
);

CREATE TABLE STATUS_FATURAMENTO (
    STF_CODIGO int PRIMARY KEY,
    STF_DESCRICAO varchar(20)
);

CREATE TABLE ENDERECOS (
    END_CODIGO int PRIMARY KEY,
    END_RUA varchar(100),
    END_BAIRRO varchar(50),
    END_NUMERO int,
    END_CIDADE varchar(50),
    FK_CLI_CODIGO int
);

CREATE TABLE PRAZOS (
    PRA_CODIGO int PRIMARY KEY,
    PRA_QUANTIDADE int
);

CREATE TABLE TIPOS_CLIENTE (
    TPC_CODIGO int PRIMARY KEY,
    TPC_DESCRICAO varchar(20)
);

CREATE TABLE PRODUTOS (
    PRO_CODIGO int PRIMARY KEY,
    PRO_CODIGOBARRA int,
    PRO_NOME varchar(50),
    PRO_FABRICANTE varchar(50),
    PRO_PRECO199 float,
    PRO_PRECOMERCADO float,
    PRO_ULTIMA_VENDA date,
    PRO_QUANTIDADE int,
    PRO_PONTOREPOSICAO int,
    PRO_ESTOQUE_CORREDOR int,
    PRO_ESTOQUE_COLUNA varchar(2),
    PRO_ESTOQUE_ANDAR int,
    PRO_ESTOQUE_POSICAO int,
    FK_CTP_CODIGO int
);

CREATE TABLE CATEGORIAS_PRODUTO (
    CTP_CODIGO int PRIMARY KEY,
    CTP_DESCRICAO varchar(35)
);

CREATE TABLE FORMAS_PAGAMENTO (
    FRP_CODIGO int PRIMARY KEY,
    FRP_DESCRICAO varchar(20)
);

CREATE TABLE FORNECEDOR (
    FOR_CODIGO int PRIMARY KEY,
    FOR_NOME varchar(50),
    FOR_TELEFONE bigint
);

CREATE TABLE FORMAPAGAMENTO_PRAZOS (
    FK_FRP_CODIGO int,
    FK_PRA_CODIGO int
);

CREATE TABLE PRODUTOS_FORNECEDOR (
    FK_FOR_CODIGO int,
    FK_PRO_CODIGO int
);

CREATE TABLE PEDIDOS_PRAZOS (
    FK_PED_CODIGO int,
    FK_PRA_CODIGO int
);

CREATE TABLE PEDIDOS_PRODUTOS (
    FK_PED_CODIGO int,
    FK_PRO_CODIGO int,
    
    PED_PRO_PRODUTO varchar(50),
    PED_PRO_QUANTIDADE int,
    PED_PRO_PRECO_UNITARIO float,
    PED_PRO_PRECOxQUANT float,
    PED_PRO_COMISSAO float,
);
 
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_1
    FOREIGN KEY (FK_STF_CODIGO)
    REFERENCES STATUS_FATURAMENTO (STF_CODIGO)
    ON DELETE RESTRICT;

ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_2
    FOREIGN KEY (FK_VDR_CODIGO)
    REFERENCES VENDEDORES (VDR_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_3
    FOREIGN KEY (FK_TPC_CODIGO)
    REFERENCES TIPOS_CLIENTE (TPC_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_4
    FOREIGN KEY (FK_REG_CODIGO)
    REFERENCES REGIOES (REG_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE REGIOES ADD CONSTRAINT FK_REGIOES_2
    FOREIGN KEY (FK_VDR_CODIGO)
    REFERENCES VENDEDORES (VDR_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_2
    FOREIGN KEY (FK_FRP_CODIGO)
    REFERENCES FORMAS_PAGAMENTO (FRP_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_3
    FOREIGN KEY (FK_VDR_CODIGO)
    REFERENCES VENDEDORES (VDR_CODIGO)
    ON DELETE CASCADE;
 
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_4
    FOREIGN KEY (FK_CLI_CODIGO)
    REFERENCES CLIENTES (CLI_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE ENDERECOS ADD CONSTRAINT FK_ENDERECOS_2
    FOREIGN KEY (FK_CLI_CODIGO)
    REFERENCES CLIENTES (CLI_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_2
    FOREIGN KEY (FK_CTP_CODIGO)
    REFERENCES CATEGORIAS_PRODUTO (CTP_CODIGO)
    ON DELETE RESTRICT;

/* NOME DA TABELA DA FK | NOME/Nº DA RELAÇÃO */
/* NOME DA FK 			             */
/* NOME DA TABELA DA PK | NOME DA PK	     */
 
ALTER TABLE FORMAPAGAMENTO_PRAZOS ADD CONSTRAINT FK_FORMAPAGAMENTO_PRAZOS_1
    FOREIGN KEY (FK_PRA_CODIGO)
    REFERENCES PRAZOS (PRA_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE FORMAPAGAMENTO_PRAZOS ADD CONSTRAINT FK_FORMAPAGAMENTO_PRAZOS_2
    FOREIGN KEY (FK_FRP_CODIGO)
    REFERENCES FORMAS_PAGAMENTO (FRP_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE PRODUTOS_FORNECEDOR ADD CONSTRAINT FK_PRODUTOS_FORNECEDOR_1
    FOREIGN KEY (FK_FOR_CODIGO)
    REFERENCES FORNECEDOR (FOR_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE PRODUTOS_FORNECEDOR ADD CONSTRAINT FK_PRODUTOS_FORNECEDOR_2
    FOREIGN KEY (FK_PRO_CODIGO)
    REFERENCES PRODUTOS (PRO_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE PEDIDOS_PRAZOS ADD CONSTRAINT FK_PEDIDOS_PRAZOS_1
    FOREIGN KEY (FK_PED_CODIGO)
    REFERENCES PEDIDOS (PED_CODIGO)
    ON DELETE SET NULL;
 
ALTER TABLE PEDIDOS_PRAZOS ADD CONSTRAINT FK_PEDIDOS_PRAZOS_2
    FOREIGN KEY (FK_PRA_CODIGO)
    REFERENCES PRAZOS (PRA_CODIGO)
    ON DELETE SET NULL;
 
ALTER TABLE PEDIDOS_PRODUTOS ADD CONSTRAINT FK_PEDIDOS_PRODUTOS_1
    FOREIGN KEY (FK_PRO_CODIGO)
    REFERENCES PRODUTOS (PRO_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE PEDIDOS_PRODUTOS ADD CONSTRAINT FK_PEDIDOS_PRODUTOS_2
    FOREIGN KEY (FK_PED_CODIGO)
    REFERENCES PEDIDOS (PED_CODIGO)
    ON DELETE SET NULL;